apiVersion: v2
appVersion: 1.8.0-SNAPSHOT
description: 'A Helm chart for deploying the Elastic Cloud on Kubernetes (ECK) operator: the official Kubernetes operator for orchestrating Elasticsearch, Kibana, APM Server, Enterprise Search, and Beats.'
home: https://github.com/elastic/cloud-on-k8s
icon: https://helm.elastic.co/icons/eck.png
keywords:
- Elasticsearch
- Kibana
- APM Server
- Beats
- Enterprise Search
- Elastic Stack
- Operator
kubeVersion: '>=1.12.0-0'
maintainers:
- email: support@beyondcent.com
  name: bocloud
  url: http://www.bocloud.com.cn
name: eck-cluster
type: application
version: 8.0.0
annotations:
  dependent-components: exporter,kibana,apmserver
  # 核心组件
  core-components: elasticsearch

