{{ if .Values.apmserver.enabled -}}
apiVersion: maps.k8s.elastic.co/v1
kind: ElasticMapsServer
metadata:
  name: apmserver-{{ .Release.Name }}
spec:
  version: {{ .Values.version }}
  count: 1
  config:
    logging.level: trace
  elasticsearchRef:
    name: "{{ .Release.Name }}"
  kibanaRef:
    name: kibana-{{ .Release.Name }}
  http:
    service:
      spec:
        type: {{ .Values.apmserver.serviceType}}
  podTemplate:
    metadata:
      labels:
        boc.cloud.com/name: apmserver
    spec:
      containers:
      - name: apmserver
        image: {{ .Values.apmserver.image}}   
      resources:
        requests:
          cpu: {{ .Values.apmserver.resources.requests.cpu}}
          memory: {{ .Values.apmserver.resources.requests.memory}}
        limits:
          cpu: {{ .Values.apmserver.resources.limits.cpu}}
          memory: {{ .Values.apmserver.resources.limits.memory}}
 {{ end -}}      