{{ if .Values.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-elasticsearch-realm-secret
type: Opaque
stringData:
  users: |-
    rdeniro:$2a$10$BBJ/ILiyJ1eBTYoRKxkqbuDEdYECplvxnqQ47uiowE7yGqvCEgj9W
    alpacino:$2a$10$cNwHnElYiMYZ/T3K4PvzGeJ1KbpXZp2PfoQD.gfaVdImnHOwIuBKS
    jacknich:{PBKDF2}50000$z1CLJt0MEFjkIK5iEfgvfnA6xq7lF25uasspsTKSo5Q=$XxCVLbaKDimOdyWgLCLJiyoiWpA/XDMe/xtVgn1r5Sg=
  users_roles: |-
    admin:rdeniro
    power_user:alpacino,jacknich
    user:jacknich

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-elasticsearch-roles-secret
type: Opaque
stringData:
   roles.yml: |-
	  click_admins:
	    run_as: [ 'clicks_watcher_1' ]
	   	cluster: [ 'monitor' ]
	   	indices:
	   	- names: [ 'events-*' ]
	   	  privileges: [ 'read' ]
	   	  field_security:
	   		grant: ['category', '@timestamp', 'message' ]
	   	  query: '{"match": {"category": "click"}}'
	  another_role:
	      cluster: [ 'all' ]

 {{ end -}}      